### PR TITLE
Fix trigger property

### PR DESCRIPTION
**Pull request by james-ai**
Trigger couldn't handle values like:
TRIGGER;VALUE=DURATION:-PT15M

This fixes that.

### CODE REVIEW

**Comment by ericcf** [comment]
Would you do me a favor and add/modify a spec to cover this? Thanks.

**Comment by james-ai** [comment]
Yeah. Should've done that anyway.

**Comment by james-ai** [comment]
The tests are failing because DTSTAMP and UID are being set somewhere else it seems. Any thoughts?

**Comment by james-ai** [comment]
Just to say that the tests were passing before I submitted the changes.

**Comment by james-ai** [comment]
Okay so the tests seem to pass and fail at random under 1.8.7 and 1.9.3. Interestingly under 1.8.7 there are 52 tests and under 1.9.3 there are 53. 

Any of this make sense to you?

**Comment by ericcf** [comment]
The character_set_spec.rb file contains a test that doesn't run under 1.8.7. This brings up a point: do you need this to run under 1.8.7? If not, it may be worth just dropping 1.8.7 support.

**Comment by james-ai** [comment]
No need for this to run under 1.8.7. 

If you drop support for 1.8.7 I suppose we can just leave an issue open if someone comes along and does need this to run under 1.8.7.

Any idea why my test fails the first time round but pass thereafter? I've no experience with Spec so could be something stupid I've done.

**Comment by ericcf** [comment]
In the `.rspec` file, I've set the flag `--order rand` so that the test order is random. If there are no hidden dependencies/side effects between the tests, they should always pass. The fact that there are occasional failures is a sign that there is something fishy. I'll see if I can figure it out.

**Comment by james-ai** [comment]
I've written an rspec file for the timezone changes I've made. It was similar in style to the alarm rspec and so also failed the first time (if it hadn't been run in a while).

I changed the timezone rspec to look more like the event rspec and haven't experienced the problem again. I'll avoid running the tests for the rest of today then try them again first thing tomorrow.

Here's what the timezone rspec has changed to. Previously I was declaring the calendar object at the top exactly as I'd done in the alarm rspec.

``` ruby
require 'spec_helper'

describe Icalendar2::Timezone do

  subject { Timezone.new }

  let(:ical_str) do
str = <<EOS
BEGIN:VTIMEZONE
TZID:Europe/London
BEGIN:DAYLIGHT
DTSTART:19810329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:BST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
BEGIN:DAYLIGHT
DTSTART:21170329T010000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
TZNAME:NBST
TZOFFSETFROM:+0000
TZOFFSETTO:+0100
END:DAYLIGHT
BEGIN:STANDARD
DTSTART:19961027T020000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
TZNAME:GMT
TZOFFSETFROM:+0100
TZOFFSETTO:+0000
END:STANDARD
END:VTIMEZONE
EOS
    str.gsub(/\n/, Tokens::CRLF)
  end

  it "converts to icalendar format" do
    subject.tzid = "Europe/London"
    daylight_1 = Timezone::Daylight.new
    daylight_2 = Timezone::Daylight.new
    standard = Timezone::Standard.new
    daylight_1.tzoffsetfrom = daylight_2.tzoffsetfrom = "+0000"
    daylight_1.tzoffsetto = daylight_2.tzoffsetto = "+0100"
    daylight_1.rrule = daylight_2.rrule = "FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU"
    daylight_1.dtstart = DateTime.new(1981, 03, 29, 01, 00, 00)
    daylight_1.tzname = "BST"
    daylight_2.dtstart = DateTime.new(2117, 03, 29, 01, 00, 00)
    daylight_2.tzname = "NBST"
    standard.tzoffsetfrom = "+0100"
    standard.tzoffsetto = "+0000"
    standard.rrule = "FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU"
    standard.dtstart = DateTime.new(1996, 10, 27, 02, 00, 00)
    standard.tzname = "GMT"

    subject.add_daytime_component(daylight_1)
    subject.add_daytime_component(daylight_2)
    subject.add_standard_component(standard)

    subject.to_ical.should eq(ical_str)
    subject.valid?.should eq(true)
  end

  it "is invalid to have an empty timezone" do
    cal = Calendar.new
    cal.timezone do
    end

    cal.valid?.should eq(false)
  end
end
```

I'm not sure that I can do the same thing in the alarm rspec because of the way triggers are formed with a semi-colon coming after the property word:

```
TRIGGER;VALUE=DURATION:-PT0S
```

In order to get the parameter formatted correctly it appears that triggers have to be declared inside an alarm block:

``` ruby
alarm do
  trigger "-PT0S", {"VALUE" => "DURATION"}
end
```

Again I'm not well-versed (or at all really) in rspec so all of what I've just told you could be utterly useless!

**Pull request merged**
